<?php
class DjBpmMediator extends Mediator {
	const NAME = 'DjBpmMediator';

	protected $iBpm = 0;

	public function listNotificationInterests() {
		return array(AppFacade::DJ_COMMAND_COMPLETE);
	}

	/**
	 * get the current bpm value from the notification, load our templates
	 * and provide them w/ data they need.  as well, some of the data is
	 * generated by us here.
	 */
	public function handleNotification(INotification $oNote) {
		$this->iBpm = $oNote->getBody();
		/* set template values */
		$this->sBpmGraphic = $this->renderBpmGraphic();
		include('layout.php');
	}

	/**
	 * generate a simple rendition of the current beat,
	 * +------+
	 * |....  | ex. Cur BPM: 4
	 * +------+
	 */
	protected function  renderBpmGraphic() {
		return sprintf("+%'-{$this->iBpm}s+", '') . 	// renter top
				sprintf("|%'.{$this->iBpm}s|", '') .	// render center
				sprintf("+%'-{$this->iBpm}s+", '');		// render bottom
	}
}
